### ISSUE TITLE
mobx-react Version

### ISSUE THREAD

**Issue by brian-t-allen** [miles-till/mobx-state-tree-router#2]
I'm getting this:
npm WARN mobx-state-tree-router@1.2.0 requires a peer of mobx-react@^5.0.0 but none is installed. You must install peer dependencies yourself.

I'm using mobx-react 6.1.8.

Is this something I need to be concerned about for longevity / stability of using mobx-state-tree-router?

Is there something I can do on my end to fix this (if needed)?

**Comment by miles-till** [comment]
I've updated the package to 1.3.0 to allow mobx-react ^6.0.0
